apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebooks-deployment
  labels:
    app: onlinebooks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: onlinebooks
  template:
    metadata:
      labels:
        app: onlinebooks
    spec:
      containers:
      - name: onlinebooks
        image: saikrishna7842/onlinebooks:3
        ports: 
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: onlinebooks-cluster-ip-service
spec:
  selector:
    app: onlinebooks
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
